lesson 01 fixes, lesson 02 added
CasiCode/HeadsAndHands pull request #1
Opened 2023-10-25 14:08 UTC by CasiCode

2023-10-25 18:51 UTC, DmitriyTSt requested changes

2023-10-25 18:51 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/values/strings.xml
> +    <string name="lokaleButtonText" translatable="false">Lokale</string>
locale

нотация не та, и прыгает в рамках одного файла. Для всех ресурсов кроме атрибутов и стилей - snake_case

2023-10-25 18:51 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/values/themes.xml
> +        <item name="colorPrimary">@color/state_list_button_color</item>
темы на каждый элемент лучше стараться не создавать, можно цвет назначить было у shape

2023-10-25 18:51 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/values-sw325dp/colors.xml
> +    <color name="poem_color">#820f00</color>
наоборот цвета, перепутал, тут черный должен быть

2023-10-25 18:51 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/drawable/layer_list.xml
> +    <item android:right="30dp" android:bottom="30dp">
так не 30 а 40 должно было быть везде тут, если по заданию по цифрам

2023-10-26 12:14 UTC, CasiCode commented on Lesson_02_Pitsunov/app/src/main/res/values/themes.xml
> +        <item name="colorPrimary">@color/state_list_button_color</item>
Здесь тема - костыль, потому что кнопка не меняла цвет при добавлении solid у тега shape или color у item

2023-10-26 12:18 UTC, CasiCode commented on Lesson_02_Pitsunov/app/src/main/res/drawable/layer_list.xml
> +    <item android:right="30dp" android:bottom="30dp">
По заданию есть два квадрата 60х60 и один упирается уголком ровно в центр другого. Поэтому смещение 30. Если имелось ввиду, что квадраты по разным углам холста, то, конечно, смещение будет 40. Но в этом случае иллюстрация не точная

2023-10-26 12:19 UTC, CasiCode commented on Lesson_02_Pitsunov/app/src/main/res/values-sw325dp/colors.xml
> +    <color name="poem_color">#820f00</color>
sw325dp подгружает ресурсы для устройств, у которых ширина >=325dp, верно?

2023-10-26 12:52 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/values/themes.xml
> +        <item name="colorPrimary">@color/state_list_button_color</item>
app:backgroundTint

2023-10-26 12:52 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/values-sw325dp/colors.xml
> +    <color name="poem_color">#820f00</color>
да

2023-10-26 12:52 UTC, DmitriyTSt commented on Lesson_02_Pitsunov/app/src/main/res/drawable/layer_list.xml
> +    <item android:right="30dp" android:bottom="30dp">
закрываем коммент, задание двоякое половина сделала по числам половина по рисунку

2023-10-27 05:52 UTC, DmitriyTSt approved these changes

2023-10-27 05:59 UTC, merged